import pygame
from os.path import join 
from os import walk
from random import randint, choice, shuffle

WINDOW_WIDTH, WINDOW_HEIGHT = 1280,720

COLORS = {
    'black': '#000000',
    'red': '#ee1a0f',
    'gray': 'gray',
    'white': '#ffffff',
    'blue': '#0000FF'
}

ENEMY_DATA = {
    'the-guardian': {'hp': 240,
                 'moves': {'charging up': ('gain', 20, 'block'),
                           'fierce bash': ('deal', 32),
                        #    'vent steam': (('inflicts ', 2, 'weak'), ('inflicts ', 2, 'vulnerable')),
                           'whirlwind': ('deal', 5 * 5)},
                 'moves_def': {'defensive mode': ('gain', 3, 'sharp hide'),
                           'roll attack': ('deal', 9),
                           'twin slam': (('deal', 8 * 2), ('remove', 'sharp hide'))}},
}

CARDS_DATA = {
    'Strike': {'rarity': 'starter',
               'type': 'attack',
               'energy': 1,
               'description': [('deal', 6)],
               'is_upgrade': [('deal', 9)]},
    'Bash': {'rarity': 'starter',
             'type': 'attack',
             'energy': 2,
             'description': [('deal', 8), ('apply', 2, 'vulnerable')],
             'is_upgrade': [('deal', 10), ('apply', 3, 'vulnerable')]},
    'Defend': {'rarity': 'starter',
               'type': 'skill',
               'energy': 1,
               'description': [('gain', 5, 'block')],
               'is_upgrade': [('gain', 8, 'block')]},
    'Anger': {'rarity': 'Common',
              'type': 'attack',
              'energy': 0,
              'description': [('deal', 6), ('copy', 1, 'self.discard_pile')],
              'is_upgrade': [('deal', 8)]},
    'BodySlam': {'rarity': 'Common',
              'type': 'attack',
              'energy': 1,
              'description': [('deal', 'block')],
              'is_upgrade': [('energy', 0)]},
    'Clothesline': {'rarity': 'Common',
                    'type': 'attack',
                    'energy': 2,
                    'description': [('deal', 12), ('apply', 2, 'weak')],
                    'is_upgrade': [('deal', 14), ('apply', 3, 'weak')]},
    'IronWave': {'rarity': 'Common',
                  'type': 'attack',
                  'energy': 1,
                  'description': [('gain', 5, 'block'), ('deal', 5)],
                  'is_upgrade': [('gain', 7, 'block'), ('deal', 7)]},
    'BattleTrance': {'rarity': 'Uncommon',
                      'type': 'skill',
                      'energy': 0,
                      'description': [('draw', 3)],
                      'is_upgrade': [('draw', 4)]},
    'Entrench': {'rarity': 'Uncommon',
                 'type': 'skill',
                 'energy': 2,
                 'description': [('gain', 'self.player.block * 2', 'block')],
                 'is_upgrade': [('energy', 1)]},
    'Inflame': {'rarity': 'Uncommon',
                'type': 'power',
                'energy': 1,
                'description': [('gain', 2, 'strength')],
                'is_upgrade': [('gain', 3, 'strength')]},
    'Impervious': {'rarity': 'Rare',
                   'type': 'skill',
                   'energy': 2,
                   'description': [('gain', 30, 'block'), ('exhaust',)],
                   'is_upgrade': [('gain', 40, 'block')]},
    'Juggernaut': {'rarity': 'Rare',
                   'type': 'power',
                   'energy': 2,
                   'description': [('whenever_gain', 'block', 'deal', 5)],
                   'is_upgrade': [('deal', 7)]},
}
